// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmBbCWQziMerf_2LJC96j7N_-HYwU2h9Q',
    appId: '1:388489657434:web:1469aa0b0703f1b9a0ec63',
    messagingSenderId: '388489657434',
    projectId: 'powertani-d59e4',
    authDomain: 'powertani-d59e4.firebaseapp.com',
    storageBucket: 'powertani-d59e4.firebasestorage.app',
    measurementId: 'G-KVNB9WQB51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh8Pn_jefMWWZ_VOVpYZskthEQcSjcoAE',
    appId: '1:388489657434:android:1ef35ecc56dead91a0ec63',
    messagingSenderId: '388489657434',
    projectId: 'powertani-d59e4',
    storageBucket: 'powertani-d59e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8k3o3AgWafQzWw8GpT8bk9fBnNs7MtcM',
    appId: '1:388489657434:ios:dec64bbd41738b5ba0ec63',
    messagingSenderId: '388489657434',
    projectId: 'powertani-d59e4',
    storageBucket: 'powertani-d59e4.firebasestorage.app',
    iosBundleId: 'com.example.powertani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8k3o3AgWafQzWw8GpT8bk9fBnNs7MtcM',
    appId: '1:388489657434:ios:dec64bbd41738b5ba0ec63',
    messagingSenderId: '388489657434',
    projectId: 'powertani-d59e4',
    storageBucket: 'powertani-d59e4.firebasestorage.app',
    iosBundleId: 'com.example.powertani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmBbCWQziMerf_2LJC96j7N_-HYwU2h9Q',
    appId: '1:388489657434:web:983b235fd1fbf5f6a0ec63',
    messagingSenderId: '388489657434',
    projectId: 'powertani-d59e4',
    authDomain: 'powertani-d59e4.firebaseapp.com',
    storageBucket: 'powertani-d59e4.firebasestorage.app',
    measurementId: 'G-M8V34G8D12',
  );
}
